version: '3.4'
name: niceblogger-orchestrator

services:
  niceblogger.database:
    image: postgres:latest
    container_name: niceblogger-database
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/posts-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@b.com
      - PGADMIN_DEFAULT_PASSWORD=passwd
    volumes:
      - ./.containers/db-admin:/var/lib/pgadmin
    depends_on:
      - niceblogger.database

  niceblogger.cache:
    image: redis:latest
    container_name: niceblogger-cache
    restart: always
    ports:
      - '6379:6379'

  redisinsights:
    image: redis/redisinsight:latest
    container_name: redisinsights
    restart: always
    ports:
      - 5540:5540
    volumes:
      - ./.containers/cache-admin:/var/lib/ridb
    depends_on:
      - niceblogger.cache

  niceblogger.api:
    image: ${DOCKER_REGISTRY-}nicebloggerapi
    container_name: niceblogger-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5000:5000
     - 5001:5001
    restart: on-failure 
    depends_on:
     - niceblogger.database
     - niceblogger.cache
  
  niceblogger.seq:
    image: datalust/seq:latest
    container_name: niceblogger-seq
    environment:
    - ACCEPT_EULA=Y
    ports:
    - 5341:5341
    - 8081:80 

