version: '3.4'

# Advised to use Visual Studio 2022 or Rider for local debugging purposes

# Following are profiles per scenario. Please comment/uncomment relevent section.

#-------------------------------------Windows - Debugging with Visual Studio-------------------------------------#

services:
    niceblogger.api:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=5000
          - ASPNETCORE_HTTPS_PORTS=5001
        ports:
          - "5000:5000"
          - "5001:5001"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

#-------------------------------------Windows - docker compose up-------------------------------------#

# Run following commands in Powershell
# dotnet dev-certs https -ep "$env:USERPROFILE\.aspnet\https\aspnetapp.pfx" -p passwd -q
# dotnet dev-certs https --trust -q
# For more details see https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0

# Uncomment following

# services:
#   niceblogger.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=5000
#       - ASPNETCORE_HTTPS_PORTS=5001
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=passwd
#     ports:
#       - "5000:5000"
#       - "5001:5001"
#     volumes:
#       - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
#       - ~/.aspnet/https:/https:ro

#-------------------------------------macOS - Debugging with Rider & docker compose up-------------------------------------#

# Run following commands in Terminal
# dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p passwd -q
# dotnet dev-certs https --trust -q
# For more details see https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0

# Uncomment following to run on macOS Debugging with Rider

# services:
#   niceblogger.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=5000
#       - ASPNETCORE_HTTPS_PORTS=5001
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=passwd
#     ports:
#       - "5000:5000"
#       - "5001:5001"
#     volumes:
#       - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
#       - ~/.aspnet/https:/https:ro